# site settings
title: Joanne Berry for Union Square Neighborhood Council
logo: Joanne Berry
subtitle: for Union Square Neighborhood Council
short_subtitle: for USNC
email: joannemberry10@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: pettazz
street_address: 23 Rossmore Street
city: Somerville
state: MA
zip_code: 02143
country: United States of America

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
